name: "TryHackMe Stats"
description: "Collect TryHackMe stats for a user"
inputs:
  username:
    description: "TryHackMe username"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run stats script
      shell: bash
      run: |
        ./.github/actions/tryhackme-stats/run.sh "${{ inputs.username }}"
