name: TryHackMe Stats

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Run TryHackMe stats (local action)
        uses: ./.github/actions/tryhackme-stats
        with:
          username: smmburu
