name: TryHackMe Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Update every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate TryHackMe Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          filename: metrics.svg
          plugin_tryhackme: yes
          plugin_tryhackme_user: smmburu
